### ISSUE TITLE
Misspelled method and swatch order issue

### ISSUE THREAD

**Issue by endigo9740** [bartbergmans/Palettey#2]
Hi Bart, first off thanks for creating this package. Simeon's palette generator is great. I noted they've introduced an API to easily use this as a remote service, but unfortunately this appears have some CORS issues when used with Fetch.

Anyways, that aside, there's a couple notable issues in your package I wanted to bring to your attention.

1. The `createPalleteFromColor()` contains a typo for "palette", should be `createPaletteFromColor()`
2. The returned colors are in reverse order. In plain terms, swatches 50-900 should be ordered light-dark instead of dark-light

I'd love for a quick fix if you have time, otherwise let me know. I'm not opposed to submitting a pull request with my own patch soon.

Thanks,
Chris

**Comment by bartbergmans** [comment]
Hi Chris, I don't really have much time to change this. I'd be happy to merge your PR tho!

**Comment by endigo9740** [comment]
No worries, I have given this a look. I was having a trouble replicating the issue in your Jest tests. However, after some back and forth I found the issues lies on my end. I accidentally swapped the config settings for luminance min/max like so:

```js
// I had:
lMin: 100, lMax: 5,
```

```js
// Should be:
lMin: 5, lMax: 100,
``` 

So totally my bad! Sorry for the trouble. Perhaps it's worth adding some validation for in the future though? I'll resolve on my end and mark this closed.

FYI, the typo fix should be a quick fix with find/replace. I may still send a PR for that soon, but it's a nitpick and not worth losing sleep over.
