### ISSUE TITLE
Typo in main function

### ISSUE THREAD

**Issue by GeorgeCiesinski** [bartbergmans/Palettey#3]
_First of all, I just wanted to mention that I was looking for a package that creates a 10 color palette from a primary color, so I was really happy to find this on NPM. I think this is a valuable package that way more people would use if they were aware of it. I am planning to use this for many projects as I generally use tailwind to generate palettes, and it is an annoying manual process._

Regarding this issue I opened, it is very minor, but I noticed that `createPalleteFromColor` has a typo, and should be `createPaletteFromColor` instead.

**Comment by bartbergmans** [comment]
First of all, thanks a lot for using the package! And thanks for noticing the typo. Could you make a PR for this, I will merge it afterwards!

**Comment by GeorgeCiesinski** [comment]
I just checked your closed issues and see this was reported previously. Sorry for resurrecting it. I am still new to typescript but I will try my hand at a PR to fix this.

**Comment by bartbergmans** [comment]
No problem, I think I missed it. If you need any help just contact me!

**Comment by GeorgeCiesinski** [comment]
I do need help with one thing. What is the purpose of the `index.d.ts` file? 

I have fixed the typo in `index`, `README`, `index.d.ts` and `index.test.js` and the test is completing successfully, but it doesn't seem to test the `index.d.ts` file so I'm not sure if it is used or if there is any way to test it.

**Comment by bartbergmans** [comment]
The `index.d.ts` provides TypeScript type information because the module is written in JavaScript.

**Comment by bartbergmans** [comment]
Fixed by @GeorgeCiesinski

**Comment by bartbergmans** [comment]
@GeorgeCiesinski the dependabot already fixed the package-json issue.
