### ISSUE TITLE
Question: Is the returned array supposed contain a value with two hashes?

### ISSUE THREAD

**Issue by GeorgeCiesinski** [bartbergmans/Palettey#7]
I noticed that `createPaletteFromColor` returns an array with a strange value containing two hashes for key 500:

```
// Generate a luminance palette
createPaletteFromColor("primary", "#7953e0", {
  useLightness: false,
})
```
returns
```
{
      50: "#F1EEFC",
      100: "#E4DCF9",
      200: "#C9BAF3",
      300: "#AE97EC",
      400: "#9375E6",
      500: "##7953E0",
      600: "#5325CF",
      700: "#3E1C9C",
      800: "#291368",
      900: "#150934",
    },
```

I confirmed in `index.test.js` that it is testing for this condition, but I wanted to double check if it is intended or not. If it is a bug, I wouldn't mind opening up another PR to fix it, and if not, I will adjust my own project for this. 

_Also, sorry for opening up multiple issues for this. I'm working on a project using this package so I'm discovering these as I go._

**Comment by GeorgeCiesinski** [comment]
Once you confirm whether or not this is an error and are cool with me submitting another PR to fix it, I do have one question regarding the fix. 

Going off the readme, it looks like `createPaletteFromColor` expects a hex value starting with a hash character, however, `isHex(baseColor)` returns `valid` even if the hash is missing. Despite this, providing a baseColor **without** the hash character results in successful swatches, and `index` line 84 adds a hash to swatches step 500. Providing a baseColor **with** the hash to the function results in step 500 containing 2 hashes instead of one. This makes me think the function might instead be expecting a baseColor value without the hash character and it is just a typo in the readme. So I'm not sure which of the three behaviours is desired: 

1. `createPaletteFromColor` should accept a hex with a hash character, and isHex should fail if the hash character is missing, returning null when the check is done on `index` line 21. 
2. `createPaletteFromColor` should accept a hex without a hash, which is later added on `index` line 84.
3. `createPaletteFromColor` can accept a hex with or without a hash character, adding the character if it is missing, and carrying out the function regardless.

**Comment by GeorgeCiesinski** [comment]
Hey @bartbergmans I just wanted to follow up with you about this issue to see if I should proceed with the PR and which behaviour you think I should go with.

**Comment by Alixhan** [comment]
The same error happened to me

**Comment by bartbergmans** [comment]
@GeorgeCiesinski sorry for the late reply. What solution would be your suggestion? I'm fine with you creating the PR for the fix.

**Comment by GeorgeCiesinski** [comment]
@bartbergmans no worries. I opened a PR that fixes the issue. Feel free to suggest changes if needed.

**Comment by bartbergmans** [comment]
@GeorgeCiesinski Thanks a lot for all the effort! Merged the PR.
